plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: false
            members_order: source
            show_signature_annotations: true
            show_root_heading: false
      watch:
        - formify

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - python
        - json


site_name: Formify
site_url: https://formify.readthedocs.io

nav:
  - "root": root.md
  - "Localization": localization.md

