plugins:
  - search
  - mkdocs-video:
  - mkdocstrings:
      handlers:
        python:
          paths: [formify]
          rendering:
            heading_level: 3
            show_source: false
            members_order: source
            show_signature_annotations: false
            show_root_heading: true
            show_submodules: true
            merge_init_into_class: false
          selection:
            inherited_members: true
      watch: [formify]

theme:
    name: material
    highlightjs: true
    hljs_languages:
        - python
        - json
    features:
      - content.tabs.link


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html


site_name: Formify
site_url: https://torbenfricke.github.io/formify/
site_dir: 'docs-build'

nav:
  - "Overview": index.md
  - "Gallery":
      - "People Editor": 'gallery/people.md'
      - 'gallery/matplotlib.md'
      - "Material Editor": 'gallery/material-editor.md'
      - "Pyvista Wave": 'gallery/pyvista-wave.md'
      - "Pyvista Solids": 'gallery/pyvista-solids.md'
  - "Controls": 'controls.md'
  - "Threading": 'threading.md'
  - "Localization": 'localization.md'
  - "GitHub": "https://github.com/TorbenFricke/formify"
  - "PyPi": "https://pypi.org/project/formify/"

